In [ ]:
#sale predicting

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

In [82]:
file = '/Users/sahilaggarwal/Downloads/sales_data_sample.csv'
encodings = ['utf-8', 'ISO-8859-1', 'cp1252']

for encoding in encodings:
    try:
        data = pd.read_csv(file, encoding=encoding)
        print(f"Successfully read the CSV file using encoding: {encoding}")
        break
    except UnicodeDecodeError:
        print(f"Error reading CSV file with encoding: {encoding}")

Error reading CSV file with encoding: utf-8
Successfully read the CSV file using encoding: ISO-8859-1

In [83]:
data.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [84]:
data.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [85]:
data.drop(columns=['ADDRESSLINE2','ADDRESSLINE1','ORDERDATE','STATUS','CITY','STATE','COUNTRY','TERRITORY','CONTACTLASTNAME','CONTACTFIRSTNAME','DEALSIZE','PRODUCTLINE','CUSTOMERNAME','PRODUCTCODE','PHONE','POSTALCODE'],inplace=True)

In [86]:
x=data.drop(columns=['SALES'])
y=data['SALES']

In [87]:
y.head()

0    2871.00
1    2765.90
2    3884.34
3    3746.70
4    5205.27
Name: SALES, dtype: float64

In [88]:
x.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,QTR_ID,MONTH_ID,YEAR_ID,MSRP
0,10107,30,95.70,2,1,2,2003,95
1,10121,34,81.35,5,2,5,2003,95
2,10134,41,94.74,2,3,7,2003,95
3,10145,45,83.26,6,3,8,2003,95
4,10159,49,100.00,14,4,10,2003,95

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [90]:
lr=LinearRegression()

In [91]:
lr.fit(x_train,y_train)

LinearRegression()

In [92]:
pred=lr.predict(x_test)

In [93]:
pred

array([ 1.32605578e+03,  2.68773587e+03,  4.78869531e+03,  4.83906150e+03,
        3.41441064e+03,  6.14892610e+03,  3.88856112e+03,  1.53926207e+03,
        2.55750644e+03,  7.22642607e+03,  2.89843648e+03,  2.71983629e+03,
       -8.99089912e+02,  4.80191204e+03,  5.37756265e+03,  5.27437674e+03,
        1.25788776e+03,  5.88335342e+03,  2.01024355e+03, -1.01766985e+02,
        5.28539435e+03,  3.63352126e+03,  6.94817236e+03,  1.03832005e+03,
        8.02427222e+02,  5.46942617e+03, -6.55780217e+02,  5.33406216e+03,
        2.94377621e+03,  2.92696321e+03,  3.96974516e+03,  4.71183579e+03,
        3.53151883e+03,  2.61458300e+03,  4.62391335e+03, -4.16230751e+02,
        1.75901595e+03,  2.43280123e+03,  3.12722142e+03,  5.04988934e+03,
        5.72730574e+03,  3.64076195e+03,  3.88355265e+03,  1.26716513e+03,
        3.76885426e+03,  3.96850470e+03,  4.43409279e+03,  4.27710983e+03,
        5.06361023e+03,  2.27955216e+03, -9.37507704e+02,  4.81865431e+03,
        2.47290805e+03,  2.01486665e+03,  2.97704272e+03, -6.19151524e+02,
        1.93174903e+02, -1.90236078e+02,  5.12243582e+03,  2.85151725e+03,
        1.10469204e+03,  4.07674807e+03,  1.07071134e+03,  5.01068288e+03,
        4.29329767e+03,  5.68320151e+03,  2.68207177e+03,  2.40471583e+03,
        3.92305546e+03,  2.56023269e+03,  2.67458843e+03,  5.21129176e+03,
        4.97355710e+03,  5.10618402e+03,  9.56619044e+02,  1.46530380e+03,
        3.58596542e+03,  3.80959435e+03,  4.38433340e+03,  4.54885674e+03,
        3.41313955e+03,  3.45444012e+03,  3.98458552e+03,  5.73963040e+03,
        4.09114831e+03,  4.95683628e+03,  4.79062520e+03,  3.59089093e+03,
        3.72481016e+03,  5.06046521e+03,  3.03375364e+03,  4.19194930e+03,
        5.41877963e+03,  5.07569989e+03,  2.45228066e+03,  9.04447768e+02,
        5.08269498e+03,  5.61805353e+03,  5.46062636e+03,  1.18490544e+03,
        4.59214534e+03,  3.17734979e+03,  2.61390139e+03,  2.39246620e+03,
        3.37062484e+03,  4.73224051e+03,  2.40464366e+03,  3.06162049e+03,
        5.68459030e+03,  2.07742842e+03,  1.27045595e+03,  2.47526047e+03,
        2.52993471e+03,  3.76689732e+03,  3.10801465e+03,  6.01412465e+03,
        5.02904641e+03,  5.00143124e+03,  3.59448576e+03,  6.82764186e+03,
        1.86671154e+03,  5.10496704e+03, -5.51331228e+00,  2.97578324e+03,
        2.64656549e+03,  6.11878436e+03,  3.89486271e+03,  4.76010793e+03,
        2.39457632e+02,  5.88760000e+03,  2.61067314e+03, -4.06650587e+01,
        6.77437989e+03,  3.85099015e+03,  4.43795685e+03,  3.20014035e+03,
        3.39251033e+03,  6.77368768e+03,  5.55472818e+03,  2.96051782e+03,
        2.22942045e+03,  3.23871698e+03,  4.29351845e+03,  1.96212496e+03,
        6.38079714e+03,  2.50029076e+03,  4.01419925e+03,  3.76320427e+03,
        3.65042269e+03,  4.75884398e+03,  3.25190107e+03,  1.26827723e+03,
        1.43979297e+03,  1.70745148e+02,  3.34147911e+03,  5.86323442e+03,
        1.30235443e+03,  5.70793011e+03,  4.10215887e+03,  3.48776287e+03,
        2.79414436e+03,  7.52440045e+02,  4.96023397e+03,  3.75985914e+03,
        3.72538088e+03,  1.84910888e+03,  3.18944008e+03,  2.39157240e+03,
        2.68439726e+03,  5.77571704e+03,  3.79712101e+03,  3.77273870e+03,
        8.71092221e+02,  7.14264590e+03,  2.94513177e+03,  5.55577946e+03,
        3.49152315e+03,  3.14307430e+03,  4.30256513e+03,  9.68929598e+02,
        5.46637523e+03,  1.01842751e+03,  3.73041542e+03,  6.16736797e+03,
        4.02029990e+03,  7.06391598e+03,  5.20103870e+03,  6.01950229e+03,
        4.45425561e+03,  2.96463083e+03,  3.74057160e+03,  3.20583102e+03,
        2.05561516e+02,  5.93432138e+03,  2.95059128e+03,  4.19329352e+03,
        4.00008673e+03,  1.00937083e+03,  3.97319367e+03,  3.67126992e+03,
        5.08521240e+03,  5.13256697e+03,  3.75964416e+03,  3.12185299e+03,
        1.77564488e+03,  1.50582811e+03,  3.13357866e+03,  4.09756356e+03,
        5.52131439e+03,  3.37786108e+03,  3.53189980e+03,  1.21731501e+03,
        1.45576636e+03,  2.40727565e+03, -6.78395563e+01,  4.43831339e+03,
        4.74880519e+03,  6.09592877e+03,  4.27011680e+03,  2.82990294e+03,
        1.35398752e+03,  3.60148785e+03,  3.88188712e+03,  2.02525310e+03,
        4.76244420e+03,  3.91346574e+03,  4.17895908e+02,  1.84164068e+03,
        4.28447243e+03,  1.49789557e+03,  1.01691875e+03,  5.72416260e+03,
        6.53619046e+03,  2.86080823e+03,  6.05929809e+03,  2.61868917e+03,
        3.80882584e+03,  4.64991197e+03,  4.35649557e+03,  4.49408651e+03,
        1.65877853e+03,  7.90875088e+02,  5.23809956e+03,  5.61764507e+03,
        2.14771433e+03,  3.65734964e+03,  5.72362702e+03,  5.40048714e+03,
        4.69850075e+03,  1.59360714e+03,  2.49444184e+03,  1.77509007e+03,
        3.23140214e+03,  2.70284719e+03,  2.85725525e+03,  3.14596626e+03,
        5.07602035e+03,  6.60347587e+01,  3.94362993e+03,  4.29828592e+03,
        2.02978446e+03,  4.69332256e+03,  4.13148454e+03,  4.48776081e+03,
        4.40309424e+03,  3.15552401e+03,  1.99858687e+03,  2.38890816e+03,
        6.31946332e+03,  8.72655483e+02,  1.22321134e+03,  3.87560193e+03,
        3.13776277e+03,  4.71795168e+03,  4.73797690e+03,  1.71859514e+03,
        1.50154255e+03,  4.98452167e+03,  5.52071353e+03,  4.07069928e+03,
        5.61643601e+03,  1.09639917e+03,  4.69355525e+03,  6.30768476e+03,
        5.95986271e+03,  1.31653524e+03,  6.69470341e+03,  2.81974085e+03,
        4.09289283e+03,  2.65547643e+03,  1.65573782e+03,  6.89299517e+03,
        6.16104318e+03,  3.71703706e+03,  7.00723446e+03,  6.55552338e+03,
        5.81624775e+03,  5.74454654e+03,  4.70200438e+03,  6.24195010e+03,
        4.51904338e+03,  1.81059306e+03,  4.68803401e+03,  5.62220152e+03,
        3.45598099e+03,  2.67419019e+03,  4.38272535e+03,  3.01424214e+03,
        2.61298218e+03,  5.01714592e+03,  2.60989707e+03,  3.41166857e+03,
        2.87230099e+03,  4.41098883e+03,  3.63394569e+03,  5.16322928e+03,
        2.88734406e+03,  6.00239306e+03,  1.43055895e+03, -1.13602152e+03,
        3.63929852e+03, -1.22948015e+03,  5.25068111e+03,  4.54347553e+03,
        4.04060997e+03,  2.46845089e+03,  3.05522962e+03,  1.64189919e+03,
        4.38116768e+03,  7.54969833e+02,  2.10528983e+03,  4.27191226e+03,
        1.27510757e+03,  5.42112510e+03, -4.66539740e+02,  3.52186757e+03,
        2.34582604e+03,  4.41625782e+03,  5.04823017e+03,  6.13108591e+03,
        5.56556712e+03,  3.04903540e+03,  2.17426753e+02,  2.86729297e+03,
        5.35835059e+03,  2.48300168e+03,  1.63715080e+03,  6.39272794e+03,
        1.25268209e+03,  3.98377117e+03,  1.63498592e+03,  2.73093932e+03,
        4.41988948e+03,  4.12344761e+03,  3.27207880e+03,  5.60901272e+03,
        1.89200720e+02,  1.20052591e+03,  1.59308895e+02,  4.16382373e+03,
        5.02414320e+03,  7.72879030e+03,  3.65389857e+03,  5.46508290e+03,
        4.88154268e+03,  4.77794834e+03,  4.84401932e+02,  3.25882564e+03,
        3.56968044e+03,  6.09181386e+02,  3.68961214e+03,  4.40899591e+03,
        4.99843952e+03,  2.97981239e+03,  3.41481102e+03,  3.81522834e+03,
        3.07377505e+03,  4.54102093e+03,  1.70479708e+03,  3.02525079e+03,
        3.65083006e+03,  4.32481987e+03,  4.92569725e+03,  3.76234392e+03,
        4.39224466e+03,  2.78248733e+03,  3.56271938e+03,  2.79795351e+03,
        2.54177871e+03,  2.92917191e+03,  2.66576349e+03,  3.94724275e+01,
        3.23593627e+03,  1.37802718e+03,  3.42626695e+03,  4.54804742e+03,
        2.37426769e+03,  5.17320800e+03,  2.19269929e+03,  3.28168188e+03,
        3.63920965e+03,  3.37995903e+03,  2.30842093e+03,  5.11589335e+02,
        4.29548925e+03,  5.38147427e+03,  4.83899182e+03,  4.37122280e+03,
        5.29400978e+03,  3.75244370e+03,  5.74184549e+03,  3.20875584e+03,
        4.47384453e+03,  5.08243136e+03,  5.36832950e+03,  1.37157897e+03,
        3.13930200e+03,  4.70263381e+03,  3.95662080e+03,  9.42574998e+02,
        2.13318588e+03,  4.13426834e+03,  4.89529092e+03,  2.80293677e+03,
        3.90926845e+03,  4.58094935e+02,  4.97026959e+03,  5.56181911e+03,
        3.09452135e+03,  4.37614960e+03,  2.22142584e+03,  4.36470028e+03,
        5.27277763e+03,  8.60336723e+03,  2.53063970e+03,  1.45123451e+03,
        5.65759491e+03,  5.10430150e+03,  9.34039431e+03,  2.59070100e+03,
        2.61278309e+03,  1.58003168e+03,  3.84884367e+03,  3.84270536e+03,
        3.95724965e+03,  3.85399178e+03,  1.75757799e+03,  4.56614777e+03,
        5.53081029e+03,  4.79098243e+03,  3.44025453e+03,  3.99443855e+03,
       -1.93526886e+02,  7.68688935e+02,  2.90795136e+03,  4.63803273e+03,
        2.54723681e+03,  2.36436368e+03,  3.06623554e+03,  5.35017159e+03,
        3.71305601e+03,  5.35386176e+03,  2.35970515e+03,  3.85629236e+03,
        1.56186224e+03,  2.12014680e+03,  4.70562879e+03,  5.34367332e+03,
        3.86650405e+03,  5.32989265e+03,  3.56248129e+03,  5.63091236e+03,
        4.66230298e+03,  1.72934664e+02,  4.47547245e+03,  3.33649196e+03,
        2.87140756e+03,  4.35069547e+02,  1.39680506e+03,  3.99587265e+03,
        5.33176878e+03,  3.25488637e+03,  5.52749434e+03,  3.15543947e+03,
        2.23605424e+03,  5.50097298e+03,  2.21000010e+03,  5.29247463e+03,
        5.09581371e+03,  3.28740464e+03, -8.72335337e+02,  1.90108159e+03,
        2.24097619e+03,  1.68943276e+03,  4.53900552e+03,  4.55133927e+03,
        2.43661974e+03,  5.50741385e+03,  3.86471761e+03,  4.07489645e+03,
        4.37170955e+03,  5.44830915e+02,  1.06792228e+03,  4.21701214e+03,
        4.03828395e+03,  2.39960547e+03,  5.20837659e+03,  2.71688929e+03,
        1.91186743e+03,  4.46118446e+03,  4.32770744e+03,  1.68159145e+03,
        2.50890392e+03,  3.79264969e+03,  3.91211565e+03,  1.85775245e+03,
        3.20903199e+03,  1.97555126e+03,  3.43955900e+03,  2.02696494e+03,
        5.66541134e+03,  3.42922174e+03,  4.63503265e+03,  4.24037228e+03,
        5.38159207e+03,  4.65288095e+03,  4.98565464e+03,  5.25499006e+03,
        3.89181545e+03,  1.73807088e+03,  5.24654124e+03,  1.17566068e+03,
        3.09648349e+03,  3.20248681e+03,  1.74179668e+03,  5.62154123e+03,
        3.46432961e+03,  2.71326182e+03,  3.14952684e+03,  4.79145474e+03,
        9.05818905e+02,  2.84152966e+03,  2.19440497e+03,  3.30448437e+03,
        1.75910808e+03,  2.88812303e+03,  4.21297059e+03,  3.83652769e+03,
        3.83562861e+03,  4.15868614e+03,  3.80644043e+03,  3.23332797e+03,
        3.33250059e+03,  3.05687467e+03,  3.63593003e+03,  2.13571277e+03,
        5.99725648e+03,  5.93348841e+03,  6.20332324e+03,  3.79468139e+03,
        6.04426739e+03,  1.71565168e+03,  6.34049395e+03,  5.61812427e+03,
        1.96160068e+03])

In [95]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 1037690.1589838697